### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by gorterd** [AAfghahi/Hermes#3]
Really awesome work, Arash, keep it up! Below is my feedback:

***Functionality***
Auth, more generally
  - [x] current user is not bootstrapping correctly. When I sign in, there is a current user in the session slice of state, but that is lost upon refreshing
  - [x] once logged in, I should be redirected if I attempt to go to /signup or /login (eventually to the user dashboard, where the navbar should no look like it does for current users; for now home is fine). Not happening for me right now
- Login
  - [x] When I attempt to login with bad credentials multiple times, I see this. Should only show error message once ![error messages](https://i.imgur.com/gtyYlTY.png)
  - [x] link to sign up from login page is broken
- Sign up
  - Do you eventually plan to implement the modal right after signing up, where the user puts in their birth date, weight etc?

***Styling***
- Splash
  - [x] add a grey line below the navbar & increase the size of the header text
  - [x] add 'Already a member? Log in' below the sign up buttons, as in the real Strava
  - [x] the sign up / demo buttons should look a bit closer to the real Strava (narrower, smaller text)
  - optional: replicate the appearance of the footer more closely by having lists of some sort (could be informational, such as technologies used in this clone or skills you have as a web developer) 
- Login / Sign up
  - [x] placeholder text in the inputs should be lighter
  - [x] when an input is selected, it should have a light background with dark text, like Strava
  - [x] font for header should approximate Strava more closely
  - [x] login error messages should look more like Strava's --> e.g. red background, white text (could use that same style for sign up messages, since Strava's sign up errors are rendered next to the relevant inputs which we don't require)
  - [x] login only: button to 'Sign Up' in upper right should be orange

**Comment by AAfghahi** [comment]
Did everything but errors, changed the login/sign up pages, bootstrapping correctly now. 

I will be sending them to the routes home page, and yeah when I get to user's show page I am going to make that a one time modal for sure.

**Comment by gorterd** [comment]
Really nice work on the revisions, Arash! 

There's just one other change I think you should make -- didn't see it last time. When I sign up with empty inputs, the errors messages appear side by side in a way that doesn't feel intentional. I'd suggest putting them on separate lines. ![](https://i.imgur.com/tLLcUmu.png)

Also, I think it's fine if you don't worry too much about the error messages being inside a red box, but just a heads up that it's a bit difficult to read now, might make the text a little lighter.
